/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentalPS_Form;

import javax.swing.*;
import javax.swing.table.*;
import java.sql.*;
import java.text.*;
import java.util.*;



/**
 *
 * @author Dhafi
 */
public class rentalPS_Form extends javax.swing.JFrame {
   
//    Variable Untuk Konek ke database
   private static final String username = "root";
   private static final String password = "";
   private static final String dataCon = "jdbc:mysql://localhost:3306/dbrentalps";
   
   Connection sqlConn = null;
   PreparedStatement pst = null;
   ResultSet rs = null;
   
   int q,i;
    
    public rentalPS_Form() {
        initComponents();
        updateDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
//    ========================================== database ======================================================
    
    public void updateDb(){
        
//        Buat Table Gk bisa di Edit
//    DefaultTableModel tableModel = new DefaultTableModel() {
//
//        @Override
//        public boolean isCellEditable(int row, int column) {
//           //all cells false
//           return false;
//        }
//    };
//
//    jTable1.setModel(tableModel);
        
        
        try
        {
            
            Class.forName("com.mysql.jdbc.Driver");
//            Konek Ke database
            sqlConn = DriverManager.getConnection(dataCon,username,password);
//            Statement Select
            pst = sqlConn.prepareStatement("SELECT * FROM `rental` , `paket` WHERE rental.id_paket = paket.id_paket ORDER BY id_rental ASC");
            
//            Jalanin Query
            rs = pst.executeQuery();
//            Hasil Query
            ResultSetMetaData stData = rs.getMetaData();
            
            q = stData.getColumnCount();
            
//            Buat Row 
            DefaultTableModel RecordTable =  (DefaultTableModel)jTable1.getModel();
            RecordTable.setRowCount(0);
            
//            Fetch Query
            while(rs.next()){
                Vector dataColom = new Vector();
                
                for(i=1;i <= q;i++){
                    dataColom.add(rs.getInt("id_rental"));
                    dataColom.add(rs.getString("nama"));
                    dataColom.add(rs.getString("no_telp"));
                    dataColom.add(rs.getString("email"));
                    dataColom.add(rs.getString("alamat"));
                    dataColom.add(rs.getString("nama_paket"));
                    dataColom.add(rs.getInt("harga"));
                    dataColom.add(rs.getString("created_at"));
                };
                
                RecordTable.addRow(dataColom);
            }
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    
    
    
    //    ========================================== end database ======================================================

    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxtNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtTelp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtAlamat = new javax.swing.JTextField();
        jcmbPaket = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jbtnTambah = new javax.swing.JButton();
        jbtnEdit = new javax.swing.JButton();
        jbtnHapus = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 8));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 8));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Nama");

        jtxtNama.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("No. Telp");

        jtxtTelp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Email");

        jtxtEmail.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Alamat");

        jtxtAlamat.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jcmbPaket.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jcmbPaket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reguler", "Eksklusif", "Bulanan" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Paket");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "No_Telp", "Email", "Alamat", "Paket", "Harga", "created_at"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jcmbPaket, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 220, Short.MAX_VALUE))
                            .addComponent(jtxtTelp)
                            .addComponent(jtxtNama)
                            .addComponent(jtxtAlamat))
                        .addGap(128, 128, 128))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcmbPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 8));

        jbtnTambah.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnTambah.setText("Tambah");
        jbtnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTambahActionPerformed(evt);
            }
        });

        jbtnEdit.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnEdit.setText("Edit");
        jbtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditActionPerformed(evt);
            }
        });

        jbtnHapus.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnHapus.setText("Hapus");
        jbtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHapusActionPerformed(evt);
            }
        });

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jbtnPrint.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnHapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnPrint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnTambah, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jbtnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel1.setText("Data Rental PS");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel1)
                .addContainerGap(295, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTambahActionPerformed
        if (jtxtNama.getText().length()==0 && jtxtTelp.getText().length()==0
                && jtxtEmail.getText().length()==0 && jtxtAlamat.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Form Data Harus Terisi!");
        }else{
            try{
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataCon,username,password);
            pst = sqlConn.prepareStatement("INSERT INTO rental(id_paket,nama,no_telp,email,alamat) VALUE (?,?,?,?,?)");
            
            pst.setInt(1, jcmbPaket.getSelectedIndex());
            pst.setString(2, jtxtNama.getText());
            pst.setString(3, jtxtTelp.getText());
            pst.setString(4, jtxtEmail.getText());
            pst.setString(5, jtxtAlamat.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Berhasil Ditambah!");
            updateDb();
            
            }

            catch(ClassNotFoundException ex){
                java.util.logging.Logger.getLogger(rentalPS_Form.class.getName()).log(java.util.logging.Level.SEVERE, null , ex);   
            }
            catch(SQLException ex){
                java.util.logging.Logger.getLogger(rentalPS_Form.class.getName()).log(java.util.logging.Level.SEVERE, null , ex);  
            }
        }
        
    }//GEN-LAST:event_jbtnTambahActionPerformed

    private JFrame frame;
    
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame = new JFrame("Exit");
        
        if(JOptionPane.showConfirmDialog(frame, "Anda Yakin Untuk Keluar?" , "Data Rental PS", 
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        jtxtNama.setText("");
        jtxtTelp.setText("");
        jtxtEmail.setText("");
        jtxtAlamat.setText("");
        jcmbPaket.setSelectedItem("");
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditActionPerformed
        if (jtxtNama.getText().length()==0 && jtxtTelp.getText().length()==0
                && jtxtEmail.getText().length()==0 && jtxtAlamat.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Form Data Harus Terisi!");
        }else{
            try{
            DefaultTableModel RecordTable =  (DefaultTableModel)jTable1.getModel();
            int selectedRow = jTable1.getSelectedRow();
            String id_paket = RecordTable.getValueAt(selectedRow, 0).toString();

                    
            
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataCon,username,password);
            pst = sqlConn.prepareStatement("UPDATE rental SET id_paket = ? ,nama = ? , no_telp = ?, email = ? , alamat = ? WHERE id_rental = ?");
            
            pst.setInt(1, jcmbPaket.getSelectedIndex());
            pst.setString(2, jtxtNama.getText());
            pst.setString(3, jtxtTelp.getText());
            pst.setString(4, jtxtEmail.getText());
            pst.setString(5, jtxtAlamat.getText());
            pst.setInt(6, Integer.valueOf(id_paket));
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Berhasil Diedit!");
            updateDb();
            
            }

            catch(ClassNotFoundException ex){
                java.util.logging.Logger.getLogger(rentalPS_Form.class.getName()).log(java.util.logging.Level.SEVERE, null , ex);   
            }
            catch(SQLException ex){
                java.util.logging.Logger.getLogger(rentalPS_Form.class.getName()).log(java.util.logging.Level.SEVERE, null , ex);  
            }
        }
        
    }//GEN-LAST:event_jbtnEditActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel RecordTable =  (DefaultTableModel)jTable1.getModel();
        int selectedRow = jTable1.getSelectedRow();
        
        jtxtNama.setText(RecordTable.getValueAt(selectedRow, 1).toString());
        jtxtTelp.setText(RecordTable.getValueAt(selectedRow, 2).toString());
        jtxtEmail.setText(RecordTable.getValueAt(selectedRow, 3).toString());
        jtxtAlamat.setText(RecordTable.getValueAt(selectedRow, 4).toString());

    }//GEN-LAST:event_jTable1MouseClicked

       private JFrame confirmdelete;
    
    private void jbtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHapusActionPerformed
        DefaultTableModel RecordTable =  (DefaultTableModel)jTable1.getModel();
        int selectedRow = jTable1.getSelectedRow();
        
        int id_rental = Integer.parseInt(RecordTable.getValueAt(selectedRow, 0).toString());
        
        try{            
            if (JOptionPane.showConfirmDialog(confirmdelete, "Anda Yakin Untuk Menghapus Data ini?" , "Warning", 
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                Class.forName("com.mysql.jdbc.Driver");
                sqlConn = DriverManager.getConnection(dataCon,username,password);
                pst = sqlConn.prepareStatement("DELETE FROM rental WHERE id_rental = ?");

                pst.setInt(1, id_rental);
                
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus!");
                updateDb();
                
                
                jtxtNama.setText("");
                jtxtTelp.setText("");
                jtxtEmail.setText("");
                jtxtAlamat.setText("");
            }
        }
        catch(ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(rentalPS_Form.class.getName()).log(java.util.logging.Level.SEVERE, null , ex);   
        }
        catch(SQLException ex){
            java.util.logging.Logger.getLogger(rentalPS_Form.class.getName()).log(java.util.logging.Level.SEVERE, null , ex);  
        }

    }//GEN-LAST:event_jbtnHapusActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        MessageFormat header = new MessageFormat("Printing In Progress");
        MessageFormat footer = new MessageFormat("Page {0, number, integer}");
        
        try{
            jTable1.print(JTable.PrintMode.NORMAL,header,footer);
        }
        catch (java.awt.print.PrinterException ex){
            System.err.format("No Printer Found ", ex.getMessage());
        }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rentalPS_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rentalPS_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rentalPS_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rentalPS_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rentalPS_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnEdit;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnHapus;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnTambah;
    private javax.swing.JComboBox<String> jcmbPaket;
    private javax.swing.JTextField jtxtAlamat;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtNama;
    private javax.swing.JTextField jtxtTelp;
    // End of variables declaration//GEN-END:variables
}
